name: soul_saver
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  firebase_core: ^2.13.0
  firebase_database: ^10.2.1
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  url_launcher: ^6.1.11
  awesome_dialog: ^3.0.2
  awesome_notifications_fcm: ^0.7.4+1
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.4


  flutter: 
    sdk: flutter
  get: ^4.3.8

dev_dependencies:
  sqflite: ^2.0.0
  path: ^1.8.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
   image_path: "assets/images/img.png"
   android: true
   ios: true
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
        - asset: assets/fonts/MontserratRomanRegular.ttf
          weight: 400
    - family: DM Sans
      fonts: 
        - asset: assets/fonts/DMSansMedium.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Segoe UI
      fonts: 
        - asset: assets/fonts/SegoeUI.ttf
          weight: 400
